[package]
name = "vbzli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
futures = "0.3.31"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
xml = "0.8.20"
